# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    upload_to_lambdatest(
      lt_username: ENV["LT_USERNAME"],
      lt_access_key: ENV["LT_ACCESS_KEY"],
     file_path: "apk_file_path"
    )
   gradle(task: "test")
  end
end
